version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
      - ./output:/app/output
    environment:
      - QWEN_ASR_API_KEY=${QWEN_ASR_API_KEY}
